// <auto-generated />
using CLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CLab.Migrations
{
    [DbContext(typeof(ClabDbContext))]
    [Migration("20260618082606_StatoClienteReferentePrincipale")]
    partial class StatoClienteReferentePrincipale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("CLab.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitaIva")
                        .HasColumnType("TEXT");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Referente")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("CLab.Models.Contatti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Etichetta")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Principale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Valore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Contatti");
                });

            modelBuilder.Entity("CLab.Models.Contatti", b =>
                {
                    b.HasOne("CLab.Models.Cliente", "Cliente")
                        .WithMany("Contatti")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CLab.Models.Cliente", b =>
                {
                    b.Navigation("Contatti");
                });
#pragma warning restore 612, 618
        }
    }
}
