// <auto-generated />
using System;
using CLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CLab.Migrations
{
    [DbContext(typeof(ClabDbContext))]
    [Migration("20260818084008_AggiuntoPromemoria")]
    partial class AggiuntoPromemoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("CLab.Models.Attivita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NumeroEImporto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Periodicita")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TendinaRichiedeImporto")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestoLunghezzaMassima")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoCampo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Attivita");
                });

            modelBuilder.Entity("CLab.Models.AttivitaOpzione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttivitaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttivitaId");

                    b.ToTable("OpzioniAttivita");
                });

            modelBuilder.Entity("CLab.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Intermediario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitaIva")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProgrammaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferenteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoContabilita")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammaId");

                    b.HasIndex("ReferenteId");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("CLab.Models.ClienteAttivita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttivitaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAssegnazione")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttivitaId");

                    b.HasIndex("ClienteId", "AttivitaId")
                        .IsUnique();

                    b.ToTable("ClientiAttivita");
                });

            modelBuilder.Entity("CLab.Models.Compilazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttivitaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Periodo")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ValoreBooleano")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValoreNumero")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValoreTesto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttivitaId");

                    b.HasIndex("ClienteId", "AttivitaId", "Anno", "Periodo")
                        .IsUnique();

                    b.ToTable("Compilazioni");
                });

            modelBuilder.Entity("CLab.Models.Contatti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Etichetta")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Principale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Valore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Contatti");
                });

            modelBuilder.Entity("CLab.Models.Fattura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Annullata")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEmissione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nota")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReferenteId");

                    b.ToTable("Fatture");
                });

            modelBuilder.Entity("CLab.Models.Programma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Programmi");
                });

            modelBuilder.Entity("CLab.Models.Promemoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priorita")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Promemoria");
                });

            modelBuilder.Entity("CLab.Models.Referente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Referenti");
                });

            modelBuilder.Entity("CLab.Models.RitenutaAcconto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFattura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPagamentoFattura")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImportoRitenuta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ImportoVersato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Intestazione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroFattura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ravvedimento")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ScadenzaVersamento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("RitenuteAcconto");
                });

            modelBuilder.Entity("CLab.Models.AttivitaOpzione", b =>
                {
                    b.HasOne("CLab.Models.Attivita", null)
                        .WithMany("Opzioni")
                        .HasForeignKey("AttivitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CLab.Models.Cliente", b =>
                {
                    b.HasOne("CLab.Models.Programma", null)
                        .WithMany()
                        .HasForeignKey("ProgrammaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CLab.Models.Referente", null)
                        .WithMany()
                        .HasForeignKey("ReferenteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CLab.Models.ClienteAttivita", b =>
                {
                    b.HasOne("CLab.Models.Attivita", "Attivita")
                        .WithMany("ClientiAssegnati")
                        .HasForeignKey("AttivitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLab.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attivita");
                });

            modelBuilder.Entity("CLab.Models.Compilazione", b =>
                {
                    b.HasOne("CLab.Models.Attivita", "Attivita")
                        .WithMany()
                        .HasForeignKey("AttivitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLab.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attivita");
                });

            modelBuilder.Entity("CLab.Models.Contatti", b =>
                {
                    b.HasOne("CLab.Models.Cliente", null)
                        .WithMany("Contatti")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CLab.Models.Fattura", b =>
                {
                    b.HasOne("CLab.Models.Referente", null)
                        .WithMany()
                        .HasForeignKey("ReferenteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CLab.Models.RitenutaAcconto", b =>
                {
                    b.HasOne("CLab.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CLab.Models.Attivita", b =>
                {
                    b.Navigation("ClientiAssegnati");

                    b.Navigation("Opzioni");
                });

            modelBuilder.Entity("CLab.Models.Cliente", b =>
                {
                    b.Navigation("Contatti");
                });
#pragma warning restore 612, 618
        }
    }
}
